### ISSUE TITLE
cloud-api-commons

### ISSUE THREAD

**Issue by uchihashiamu** [ruoshuixuelabi/guiguspringcloud2020#1]
class CommonResult<T> 中  data属性拼写错误，  现在是dada

**Comment by ruoshuixuelabi** [comment]
没看出哪里有错，数据不是data是什么？

**Comment by uchihashiamu** [comment]
package com.atguigu.springcloud.entity; 
2 
 
3 import lombok.AllArgsConstructor; 
4 import lombok.Data; 
5 import lombok.NoArgsConstructor; 
6 
 
7 /** 
8  * @author admin 
9  */ 
10 @Data 
11 @AllArgsConstructor 
12 @NoArgsConstructor 
13 public class CommonResult<T> { 
14     private  Integer code; 
15     private  String message; 
16     private  T dada; 
17 
 
18     public CommonResult(Integer code, String message) { 
19         this.code = code; 
20         this.message = message; 
21     } 
22 }

**Comment by uchihashiamu** [comment]
第16行

**Comment by ruoshuixuelabi** [comment]
看出来了，感谢。已经修改
